### ISSUE TITLE
Missing reference to project this was copied from

### ISSUE THREAD

**Issue by localheinz** [dotsunited/php-cs-fixer-config#1]
If you take a closer look, then it's obvious that this project here was copied (or, let's say, at least inspired by) https://github.com/refinery29/php-cs-fixer-config, so what do you think about referencing it?

See for example https://github.com/prooph/php-cs-fixer-config.

**Comment by jsor** [comment]
Yes, you're right. That's an oversight by me. 👍

I'm currently on vacation and will add a note once i'm back.

**Comment by localheinz** [comment]
Thank you, @jsor!

**Comment by jsor** [comment]
Added now: https://github.com/dotsunited/php-cs-fixer-config#credits
Thanks for the report and sorry for the missing credits.
